---
sdkversion: 5.0.0
name: testex
version: '1.0'
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator8.1
  provisionprofile: ''
  codesignidentity: iPhone Developer
  entitlements: ''
  BundleIdentifier: com.rhomobile.testex
  BundleURLScheme: testex
  production:
    ipa_itunesartwork_image: ./production/iTunesArtwork.png
wp8:
  productid: ae157520-7a21-0132-fa98-606720a825c9
android:
  manifest_template: AndroidManifest.erb
  version: 2.3.3
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
wm: ''
win32:
  deployqt: '1'
  deploymsvc: '1'
extensions:
- rhoconnect-client
app_type: rhoelements
capabilities: []
